name: kimai
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.3.2
  dynamic_color: ^1.6.7
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  fpdart: ^1.1.0
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4
  google_fonts: ^5.1.0
  injectable: ^2.3.0
  injectable_generator: ^2.4.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  json_annotation: ^4.8.1
  lucide_icons: ^0.257.0
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  freezed: ^2.4.1
  isar_generator: ^3.1.0+1
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/
